using System;
using System.Collections.Generic;

namespace LODEdit
{
    internal enum LocationText
    {
        Invalid = 0,
        Forest = 1,
        Forest_2 = 2,
        Seles = 3,
        Hellena_Prison = 4,
        Prairie = 5,
        Cave = 6,
        Bale = 8,
        Indels_Castle = 9,
        Town_Of_Hoax = 10,
        Marshland = 11,
        Volcano_Villude = 12,
        Nest_Of_Dragon = 13,
        Lohan = 14,
        Shirleys_Shrine = 15,
        Kazas = 17,
        Black_Castle = 18,
        Fletz = 19,
        Twin_Castle = 20,
        Barrens = 21,
        Donau = 22,
        Valley = 23,
        Giganto_Home = 24,
        The_Queen_Fury = 26,
        Phantom_Ship = 27,
        Lidiera = 28,
        Undersea_Cavern = 29,
        Feuno = 30,
        Prison_Island = 31,
        Furni = 32,
        Evergreen_Forest = 33,
        Deningrad = 34,
        Crystal_Palace = 35,
        Neet = 36,
        Wingly_Forest = 37,
        Forbidden_Land = 38,
        Mountain_Of_Mortal_Dragon = 40,
        Kashua_Glacier = 42,
        Flanvel_Tower = 43,
        Snowfield = 44,
        Fort_Magrad = 45,
        Vellweb = 46,
        Death_Frontier = 48,
        Ulara = 49,
        Zenebatos = 50,
        Mayfil = 51,
        Rouge = 53,
        Aglis = 54,
        Divine_Tree = 55,
        Moon = 56,
        South_Of_Serdio = 256,
        North_Of_Serdio = 257,
        Tiberoa = 258,
        Illisa_Bay = 259,
        Mille_Seseau = 260,
        Gloriano = 261,
        Death_Frontier_Outside = 262,
        Endiness = 263
    }

    internal enum SaveLocation
    {
        Invalid = 0,
        Debug_Room_Disk_1 = 1,
        Debug_Room_Disk_2 = 2,
        Debug_Room_Disk_3 = 3,
        Debug_Room_Disk_4 = 4,
        Forest_Log_Bridge_Over_Chasm = 5,
        Forest_Log_Bridge_Over_River_With_Shana_Dog_Cutscene = 6,
        Forest_Path_To_Prairie_And_Hellena_Prison_Overworld = 7,
        Seles_Bootleg_Dart = 8,
        Seles_Cutscene_Overlooking_Burning_Seles = 9,
        Seles_Save_Point_Entrance_Where_Dart_Fights_2_Soldiers = 10,
        Seles_Basement_Of_Burned_Down_House_After_Second_Freugal = 11,
        Seles_Main_Area_With_Commander_Fight_And_Graveyard = 12,
        Hellena_Prison_Road_To_Prison = 13,
        Hellena_Prison_Drawbridge = 14,
        Hellena_Prison_Entrance_To_Prison_On_Horse = 15,
        Hellena_Prison_Save_Point_Lobby_Where_Merchant_Is_First_Found = 16,
        Hellena_Prison_Elevator_Floor_Level = 17,
        Hellena_Prison_Elevator_Second_Floor_With_Doors_To_Inside_Platforms = 18,
        Hellena_Prison_Spiral_Walkway_To_Outside_Prison_Towers = 19,
        Hellena_Prison_Save_Point_Outside_Prison_Towers = 20,
        Hellena_Prison_Guard_Break_Room_With_Furnace = 21,
        Hellena_Prison_Elevator_Top_Floor_Level_With_Bridge = 22,
        Hellena_Prison_Stairs_To_Outside_Prison_Towers_With_Merchant_Chests = 23,
        Hellena_Prison_Prison_Cells_Meeting_Lavitz = 24,
        Hellena_Prison_Prison_Cells_Entrance_Beside_Lavitz_Meeting = 25,
        Hellena_Prison_Prison_Cells_With_Elevator_Animation_And_Two_Enterable_Cells = 26,
        Hellena_Prison_Prison_Cells_Outside_Shanas_Cell = 27,
        Hellena_Prison_Prison_Cells_Entrance_Beside_Shana_Meeting = 28,
        Hellena_Prison_Prison_Cells_With_One_Enterable_Cell = 29,
        Hellena_Prison_Dungeon_With_Jiango = 30,
        Hellena_Prison_Room_Outside_Dungeon_With_Shanas_Key = 31,
        Hellena_Prison_First_Stairway_Up_To_Freugals_Keep_With_Stalagmites = 32,
        Hellena_Prison_Second_Stairway_Up_To_Freugals_Keep_With_Stalagmites = 33,
        Hellena_Prison_Save_Point_Outside_Freugals_Keep = 34,
        Hellena_Prison_Cutscene_Freugals_Keep_With_Albert_Before_Dawn = 35,
        Hellena_Prison_Freugals_Keep = 36,
        Hellena_Prison_Entrance_To_Prison_In_Wagon = 37,
        Prairie_Entrance_Where_Lavitz_Is_Shot_With_An_Arrow = 38,
        Prairie_Fork_In_Road_With_Tree_Sign = 39,
        Prairie_Outside_Shed = 40,
        Prairie_Inside_Shed = 41,
        Prairie_Falling_Tree_Is_Chopped_Down_With_Axe = 42,
        Prairie_Fast_River_With_Tree_Bridge = 43,
        Prairie_Exit_With_Family = 44,
        Cave_Entrance = 45,
        Cave_Sliding_Waterfall = 46,
        Cave_Skipping_Stones_Where_Lavitz_Falls = 47,
        Cave_Rock_Bridges_With_Fireflies = 48,
        Cave_Water_Platform_Steps_Outside_Snake_Room = 49,
        Cave_Capture_Frog_Minigame = 50,
        Cave_Thin_Rock_Bridge_Outside_Snake_Room = 51,
        Cave_Save_Point_Snake_Room = 52,
        Cave_Cutscene_Snake_Fight = 53,
        Cave_Cave_Ceiling_Cutaway_To_Exit = 54,
        Hellena_Prison_Cutscene_Escaping_Hellena = 57,
        Bale_Cutscene_Lavitzs_Roof = 65,
        Bale_Entrance_With_Fountain_And_Inn = 66,
        Bale_Underground_Entrance_Dran = 67,
        Bale_Outside_Lavitzs_House_With_Well = 68,
        Bale_Rock_Statue_Plaza_Marketplace_Outside_Weapon_Shop = 69,
        Bale_Alley_With_Mop_Knight_Kid_Behind_Clinic = 70,
        Bale_Save_Point_Inn = 71,
        Bale_Disc_1_Martel_House_Next_To_Lavitzs = 72,
        Bale_Lavitz_Portrait_House_Downstairs = 73,
        Bale_Lavitz_Portrait_House_Upstairs = 74,
        Bale_Underground_Room_By_Cellar_Stardust = 75,
        Bale_Room_Upstairs_From_Cellar_Stardust = 76,
        Bale_Barn = 77,
        Bale_Clinic_Patient_Rooms = 78,
        Bale_Clinic_Upstairs_Beds = 79,
        Bale_Clinic_Healing = 80,
        Bale_Lavitzs_House_First_Floor = 81,
        Bale_Lavitzs_House_Second_Floor = 82,
        Bale_Weapon_Shop = 83,
        Bale_Item_Shop = 84,
        Bale_Library = 85,
        Bale_Indels_Castle_Outside = 86,
        Indels_Castle_Bridge_Between_Towers = 87,
        Indels_Castle_Canal = 88,
        Indels_Castle_Canal_By_Dran = 89,
        Indels_Castle_First_Floor_With_Blacksmith = 90,
        Indels_Castle_Second_Floor_With_Banquet_Hall = 91,
        Indels_Castle_Third_Floor_Underneath_Throne_Room = 92,
        Indels_Castle_Throne_Room = 93,
        Indels_Castle_Balcony = 94,
        Town_Of_Hoax_Outside_Before_Attack = 95,
        Town_Of_Hoax_Watch_During_Attack = 96,
        Town_Of_Hoax_Save_Point_Outside_After_Attack = 97,
        Town_Of_Hoax_Fireplace_Stardust = 98,
        Town_Of_Hoax_Messy_House_With_Grandfather_Clock = 99,
        Town_Of_Hoax_Barracks = 100,
        Town_Of_Hoax_Church = 101,
        Town_Of_Hoax_Headquarters = 102,
        Town_Of_Hoax_Inn = 103,
        Town_Of_Hoax_Attic = 104,
        Town_Of_Hoax_Basement_With_Old_Woman_In_Rocking_Chair = 105,
        Marshland_Entrance_With_Sign = 106,
        Marshland_Fort_With_Crows = 107,
        Marshland_Outside_Fort_With_Fighting_Soldiers = 108,
        Marshland_Inside_Fort_With_Poisoned_Soldiers = 109,
        Marshland_Exit_With_Shana_Piggy_Back_Scene = 110,
        Marshland_Giant_Root_With_Magic_Signet_Stone = 111,
        Town_Of_Hoax_During_Attack_Assassin = 112,
        Town_Of_Hoax_During_Attack_Kongol = 113,
        Volcano_Villude_Entrance = 114,
        Volcano_Villude_Descent_With_Lava_Floe = 115,
        Volcano_Villude_Toothy_Hallway_With_Jump_Gap_Over_Lava = 116,
        Volcano_Villude_Toothy_Jumping_Path_To_Chest_With_Roots_From_Ceiling = 117,
        Volcano_Villude_Save_Point_Dabas_In_Background = 118,
        Volcano_Villude_Lava_Fish = 119,
        Volcano_Villude_Wounded_Virage_Room_Before = 120,
        Volcano_Villude_Fire_Bird_Room = 121,
        Volcano_Villude_Exit_No_Lava_With_Dabas_Merchant = 122,
        Volcano_Villude_Wounded_Virage_Room_After = 123,
        Nest_Of_Dragon_Entrance = 130,
        Nest_Of_Dragon_Hallway_Between_Entrance_Pit_And_Obstacle_To_Shirleys_Shrine = 131,
        Nest_Of_Dragon_Path_With_Obstacle_To_Shirleys_Shrine = 132,
        Nest_Of_Dragon_Outside_Pit = 133,
        Nest_Of_Dragon_Room_With_Healing_Pool = 134,
        Nest_Of_Dragon_Save_Point_Room_With_Seaweed_Barriers_Before_Feyrbrand = 135,
        Nest_Of_Dragon_Feyrbrand = 136,
        Lohan_Entrance = 140,
        Lohan_Rug_Buskers_With_Water_Bottle_Merchant = 141,
        Lohan_Stair_Mess_Outside_Weapon_And_Item_Shops = 142,
        Lohan_Stair_Mess_Outside_Inn_And_Clinic = 143,
        Lohan_Inside_Building_With_Planetarium = 144,
        Lohan_Inside_Building_With_Weapon_And_Item_Shops = 145,
        Lohan_Save_Point_Inside_Building_With_Inn = 146,
        Lohan_On_Rooftops = 147,
        Lohan_Dabas_House = 148,
        Lohan_Arena_Entrance = 149,
        Lohan_Save_Point_Arena_Back_Area_By_Obstacle_Course = 150,
        Lohan_Area_By_Hero_Competition_Registration = 151,
        Lohan_Monster_Conquest_Minigame = 152,
        Shirleys_Shrine_Entrance = 153,
        Shirleys_Shrine_Hub_With_Entrances_To_Puzzle_Rooms = 154,
        Shirleys_Shrine_Room_With_Ship_Wheel_And_Gold_Statue = 155,
        Shirleys_Shrine_Room_With_Silver_Statue = 156,
        Shirleys_Shrine_Enter_Puzzle_Code = 157,
        Shirleys_Shrine_Dumping_Platform_And_Stairs_With_Statues = 158,
        Shirleys_Shrine_Save_Point_Outside_Shirley_Fight = 159,
        Shirleys_Shrine_Treasure_Room = 160,
        Shirleys_Shrine_Shirley_Fight = 161,
        Shirleys_Shrine_Room_Outside_Dragoon_Spirit_Shine_With_Sigil = 162,
        Shirleys_Shrine_Cutscene_Ride_Tram_Puzzle_Code_Room = 163,
        Shirleys_Shrine_Cutscene_Ride_Tram_Gold_Statue_Room = 164,
        Shirleys_Shrine_Cutscene_Ride_Tram_Hub_Room = 165,
        Shirleys_Shrine_Cutscene_Ride_Tram_Silver_Statue_Room = 166,
        Kazas_Entrance = 171,
        Kazas_Guard_House = 172,
        Kazas_Materiel_Storage = 173,
        Kazas_Inn = 174,
        Kazas_Weapon_Shop_With_Feyrbrand_Slayer = 175,
        Kazas_Housing = 176,
        Kazas_Outside_Black_Castle_Between_Drawbridge_And_Resistance_Town = 177,
        Kazas_Outside_Resistance_Town = 178,
        Kazas_Resistance_Town_Library = 179,
        Kazas_Resistance_Town_Clinic = 180,
        Kazas_Save_Point_Popos_House = 181,
        Kazas_Tunnels_Under_Black_Castle = 182,
        Kazas_Room_Before_Tunnels = 183,
        Black_Castle_Soldier_Chase_Section = 187,
        Black_Castle_Hallway_Between_Black_Castle_Entrance_And_Drawbridge_With_Two_Ladders = 188,
        Black_Castle_Hallway_Outside_Scientists_Two_Elevators = 189,
        Black_Castle_Drawbridge = 190,
        Black_Castle_Cable_Car_With_Secret_Merchant = 191,
        Black_Castle_Entrance_To_Castle_Walls_From_Elevator = 192,
        Black_Castle_Castle_Walls_Beside_Cable_Car = 193,
        Black_Castle_Castle_Walls_With_Three_Training_Soldiers = 194,
        Black_Castle_White_And_Purple_Magic_Scientists = 195,
        Black_Castle_Dragon_Corpse_Scientist_Room = 196,
        Black_Castle_Garbage_Upper = 197,
        Black_Castle_Garbage_Lower = 198,
        Black_Castle_Dog_Scientist = 199,
        Black_Castle_Doel_Throne_Room = 200,
        Fletz_Entrance_With_Nellos_Home_And_Claires_Bridge_Day = 201,
        Fletz_Outside_Shopsclinic_And_Castle_Day = 202,
        Fletz_Inside_Nellos_Home = 203,
        Fletz_Inside_Weapon_Shop = 204,
        Fletz_Sleepless_House = 205,
        Fletz_Save_Point_Inn = 206,
        Fletz_Bar_Day = 207,
        Fletz_Bandit_Complainer_House = 208,
        Fletz_Clinic_First_Floor_Beds = 209,
        Fletz_Clinic_Healing = 210,
        Fletz_Inside_Accessory_Shop = 211,
        Fletz_Festers_House = 212,
        Fletz_Church = 213,
        Fletz_Inside_Item_Shop = 214,
        Fletz_Broken_Planetarium_Date = 215,
        Fletz_Working_Planetarium = 216,
        Fletz_Entrance_With_Nellos_Home_And_Claires_Bridge_Night = 217,
        Fletz_Outside_Shopsclinic_And_Castle_Night = 218,
        Fletz_Bar_Night = 219,
        Fletz_Cutscene_Marketplace_With_Guard_And_Albert = 220,
        Twin_Castle_Save_Point_After_Fester_Visit = 221,
        Twin_Castle_Save_Point_During_Fester_Visit = 222,
        Twin_Castle_Outside_Moon_Tower = 223,
        Twin_Castle_Queen_Fury_Before_Board = 224,
        Twin_Castle_Hallway_With_Training_Room_And_Seamstress = 225,
        Twin_Castle_Guest_Room_Day = 226,
        Twin_Castle_Guest_Room_Night = 227,
        Twin_Castle_Throne_Room_After_Fester_Visit = 228,
        Twin_Castle_Cutscene_Throne_Room_During_Fester_Visit = 229,
        Twin_Castle_Cutscene_Throne_Room_King_And_Albert = 230,
        Barrens_Entrance = 231,
        Barrens_Mappi_Ambush_Overpass = 232,
        Barrens_Exit_With_Stairs = 233,
        Fletz_Cutscene_Marketplace_With_Guard_And_Meru = 234,
        Fletz_Cutscene_Moon_That_Never_Sets_From_Festers_House = 235,
        Twin_Castle_Cutscene_Throne_Room_Lenus_Moon_Dagger = 236,
        Twin_Castle_Save_Point_Returning_Heroes = 237,
        Twin_Castle_Cutscene_Returning_Heroes_Banquet = 238,
        Donau_Entrance_Welcome_To_Donau = 239,
        Donau_Cutscene_Wink_Bandits = 240,
        Donau_Outside_Mayors_House = 241,
        Donau_Port = 242,
        Donau_Kates_House = 243,
        Donau_Church = 244,
        Donau_Save_Point_Inn = 245,
        Donau_Clinic_Healing = 246,
        Donau_Items_And_Weapons_Shop = 247,
        Donau_Mayors_House = 248,
        Donau_Bar = 249,
        Donau_Outside_Mayors_House_Meru = 250,
        Valley_Entrance_Gate_Closed = 251,
        Valley_After_Gate_Long_Platform_And_Fireflies_Exit_Tree = 252,
        Valley_After_Entering_Tree_Has_Root_To_Floating_Platforms = 253,
        Valley_Two_Upside_Down_Platforms_One_U_Shaped = 254,
        Valley_Save_Point_Room_Before_Completed_Virage = 255,
        Valley_Room_After_Completed_Virage = 256,
        Valley_Four_Circular_Floating_Platforms = 257,
        Valley_Entrance_Gate_Open = 258,
        Donau_Wedding = 259,
        Twin_Castle_Cutscene_Rouge_Send_Off = 260,
        Home_Of_Giganto_Entrance = 261,
        Home_Of_Giganto_Building_By_Entrance_With_Weapons = 262,
        Home_Of_Giganto_Rolling_Gate_And_Face_Wall = 263,
        Home_Of_Giganto_Save_Point_Stairs_To_Gehrich_And_Fireflies = 264,
        Home_Of_Giganto_Gehrich_Statue_Room_After_Fight = 265,
        Home_Of_Giganto_Cutscene_Gehrich_Chair_Statue = 266,
        Home_Of_Giganto_Basement_Under_Gehrich_Chair = 267,
        The_Queen_Fury_Save_Point_Front_Of_Ship = 276,
        The_Queen_Fury_Hub_Between_Front_Kitchen_Rooms = 277,
        The_Queen_Fury_Stairs_Between_Hub_And_Ships_Cabin = 278,
        The_Queen_Fury_Ships_Cabin = 279,
        The_Queen_Fury_Cabin_Room_With_Albert = 280,
        The_Queen_Fury_Kitchen = 281,
        The_Queen_Fury_Cabin_Room_With_Meru = 282,
        The_Queen_Fury_Large_Boiler_Room = 283,
        The_Queen_Fury_Small_Boiler_Room_With_Kongol = 284,
        The_Queen_Fury_Crows_Nest = 285,
        The_Queen_Fury_Cutscene_Haschel_Flashback_To_Claire_In_Rouge = 286,
        Phantom_Ship_Save_Point_Phantom_Ship_And_Queen_Fury_Crash_Section = 287,
        Phantom_Ship_Front_Of_Ship_On_Upper_Deck = 288,
        Phantom_Ship_Skeletons_Around_Password_Chest = 289,
        Phantom_Ship_Portrait_Room = 290,
        Phantom_Ship_Hallway_Down_Stairs_With_Will_O_Wisps_And_Two_Doors = 291,
        Phantom_Ship_Skeleton_Room_With_Chest_Up_Ladder = 292,
        Phantom_Ship_Kitchen = 293,
        Phantom_Ship_Room_With_Hole_In_Floor_And_Wall = 294,
        Phantom_Ship_Crib_Room = 295,
        Phantom_Ship_Hallway_With_Will_Owisps_To_Captain = 296,
        Lidiera_Outside_Canoe_Area = 297,
        Lidiera_Save_Point_Tent_With_Stardust = 298,
        Lidiera_Leaning_Tent = 299,
        Lidiera_Tent_With_Dog = 300,
        Undersea_Cavern_Entrance_Full = 301,
        Undersea_Cavern_Entrance_Drained = 302,
        Undersea_Cavern_Overlapping_Cave_Section = 303,
        Undersea_Cavern_Overlapping_Colorful_Section = 304,
        Undersea_Cavern_Save_Point_Colorful_Spiral_Staircase = 305,
        Undersea_Cavern_Whirlpool = 308,
        Feuno_Save_Point_Outside_Inn_Clinic_Spa = 309,
        Feuno_Marketplace_With_Vegetable_Busker = 310,
        Feuno_Port = 311,
        Feuno_Inn_Lower_Floor_Hotel_Available = 312,
        Feuno_Inn_Upper_Floor = 313,
        Feuno_Inn_Upper_Floor_Room_1_Bed = 314,
        Feuno_Spa = 315,
        Feuno_Clinic_Lobby = 316,
        Feuno_Clinic_Healing = 317,
        Feuno_Inn_Upper_Floor_Room_4_Beds = 318,
        Feuno_Inn_Lower_Floor_Full_Hotel = 319,
        Phantom_Ship_Cutscene_Sailors_Observing_Phantom_Ship = 321,
        Phantom_Ship_Cutscene_Queen_Fury_Leaving = 322,
        Prison_Island_Hallway_To_Lenus_Fight = 323,
        Prison_Island_Cutscene_Intro_ToLenus_Fight = 324,
        Prison_Island_Lenus_Fight = 325
    }

    internal class Warp
    {
        private readonly SaveData saveData;
        private const int LocationTextIndex = 0x022C;
        private const int WarpIndexRoom = 0x0324;
        private const int WarpIndexSpace = 0x0328;

        public int locationTextValue;
        public int warpValue;
        public List<LocationText> locationTextList = new List<LocationText>((LocationText[])Enum.GetValues(typeof(LocationText)));
        public List<SaveLocation> warpsList = new List<SaveLocation>((SaveLocation[]) Enum.GetValues(typeof(SaveLocation)));

        public Warp(SaveData saveData)
        {
            this.saveData = saveData;

            LoadData();
        }

        public LocationText GetLocationTextFromCode(int code)
        {
            if (Enum.IsDefined(typeof(LocationText), code))
            {
                return (LocationText)code;
            }
            return LocationText.Invalid;
        }

        public SaveLocation GetWarpFromCode(int code)
        {
            if (Enum.IsDefined(typeof(SaveLocation), code))
            {
                return (SaveLocation)code;
            }
            return SaveLocation.Invalid;
        }

        private void LoadData()
        {
            locationTextValue = saveData.Load16BitInt(LocationTextIndex);
            warpValue = saveData.Load32BitInt(WarpIndexRoom);
        }

        public void UpdateData()
        {
            saveData.Save16BitInt(LocationTextIndex, locationTextValue);
            saveData.Save32BitInt(WarpIndexRoom, 1); // TODO this is the position in the room
            saveData.Save32BitInt(WarpIndexSpace, warpValue);
        }
    }
}
